---
title: PR2 export statistics
format: gfm
---


# Version 5.1 - 2024

List of currently curated groups with the person(s) in charge



# DONE

## Archaeplastida

### Rhodophyta - Eric Salomaki
#### Ceramiales - integrated into PR2 5.1
- Number of sequences exported - annotated: 470
- Number of sequences exported - other: 112

#### Batrachospermales - integrated into PR2 5.1
- Number of sequences exported - annotated: 72
- Number of sequences exported - other: 38

### Chlorophyta
#### Chloropicophyceae - Daniel Vaulot - integrated into PR2 5.1
- Number of sequences exported - annotated: 298
- Number of sequences exported - other: 107

#### Picocystophyceae - Daniel Vaulot - integrated into PR2 5.1 
- Number of sequences exported - annotated: 19
- Number of sequences exported - other: 8

### Picozoa - Nina - integrated into PR2 5.1
- Number of sequences exported - annotated: 293
- Number of sequences exported - other: 176

## Opisthokonta
### Fungi
#### Microsporida  - Lilith -  done - to integrate into PR2 5.1
Number of sequences exported - annotated: 1345
Number of sequences exported - other: 2096

## TSAR
### Alveolata
#### Dinophyta
#####  Suessiales - Anthony -  done - to integrate into PR2 5.1
- Number of sequences exported - annotated: 542
- Number of sequences exported - other: 594

##### Gonyaulax, Alexandrium, Amphidinium, Heterocapsa, Azadinium - Huan Feng-  done - to integrate into PR2 5.1
- Number of sequences exported - annotated: 871
- Number of sequences exported - other: 421
---

# IN PROGRESS

## Archaeplastida

### Rhodophyta - Eric Salomaki
#### Gigartinales 
- Number of sequences exported - pr2 expert annotation: 237 
- Number of sequences exported - dada2 automated annotatation: 50 

### Chlorophyta
#### Ulvophyceae - Thomas Pröschold and Tanya 
- Number of sequences exported - pr2 expert annotation: 1907 
- Number of sequences exported - dada2 automated annotatation: 1480

#### Sphaeropleales - Thais Garcia da Silva - Marseille
- Number of sequences exported - pr2 expert annotation: 1783 
- Number of sequences exported - dada2 automated annotatation: 2027 

## Opisthokonta
###  Choanoflagellata  - Frank Nitsche - Köln
- Number of sequences exported - pr2 expert annotation: 546 
- Number of sequences exported - dada2 automated annotation: 1496 

### Fungi
####  Aphelidiomycota, Chytridiomycota, Monoblepharomycota - Alexei
- Number of sequences exported - pr2 expert annotation: 1414 
- Number of sequences exported - dada2 automated annotation: 1152

## TSAR
### Alveolata
#### Ciliophora
#####  Pleurostomatida - Hongbo
- Number of sequences exported - pr2 expert annotation: 175 
- Number of sequences exported - dada2 automated annotation: 289 

#####  Cyrtophoria - Hongbo 
- Number of sequences exported - pr2 expert annotation: 213 
- Number of sequences exported - dada2 automated annotation: 185

#####  Spirotrichea - Maximilian 
- Number of sequences exported - annotated: 4059
- Number of sequences exported - other: 5580

#####  Armophorea - Ivan Cepicka
- Number of sequences exported - pr2 expert annotation: 230 
- Number of sequences exported - dada2 automated annotation: 238 


#### Dinophyta


### Stramenopiles
#### MAST - Aleix Obiol and Ramon Massana
- Number of sequences exported - pr2 expert annotation: 2001 
- Number of sequences exported - dada2 automated annotation: 900 

## Haptista
###  Centroplasthelida (Centrohelids) - Daria Drachko
- Number of sequences exported - pr2 expert annotation: 158 
- Number of sequences exported - dada2 automated annotation: 175 


## Amoebozoa

###  Archamoebea - Ivan Cepicka 
- Number of sequences exported - pr2 expert annotation: 549 
- Number of sequences exported - dada2 automated annotation: 1017 


## Excavata

###  Metamonada - Ivan Cepicka 
- Number of sequences exported - pr2 expert annotation: 1656 
- Number of sequences exported - dada2 automated annotation: 1208

###  Jakobida - Ivan Cepicka 
- Number of sequences exported - pr2 expert annotation: 124 
- Number of sequences exported - dada2 automated annotation: 27

---

# EurRef workshop 2023
```

Chlorophyta
Number of sequences exported - annotated: 12184
Number of sequences exported - other: 9646
Amoebozoa
Number of sequences exported - annotated: 3331
Number of sequences exported - other: 9060

Rhodophyta
Number of sequences exported - annotated: 2458
Number of sequences exported - other: 2986

Dinophyceae
Number of sequences exported - annotated: 7591
Number of sequences exported - other: 6062
Metazoa
Number of sequences exported - annotated: 47482
Number of sequences exported - other: 88321
Fungi
Number of sequences exported - annotated: 57020
Number of sequences exported - other: 101780

Trebouxiophyceae 
- Number of sequences exported - annotated: 3072
- Number of sequences exported - other: 2424


Fungi 
- Number of sequences exported - annotated: 2536
- Number of sequences exported - other: 3238

Cnidaria 
- Number of sequences exported - annotated: 1956
- Number of sequences exported - other: 1821

Ctenophora 
- Number of sequences exported - annotated: 82
- Number of sequences exported - other: 130

Placozoa 
- Number of sequences exported - annotated: 13
- Number of sequences exported - other: 0

Porifera 
- Number of sequences exported - annotated: 1082
- Number of sequences exported - other: 480

Eumycetozoa 
- Number of sequences exported - annotated: 1122
- Number of sequences exported - other: 2239
Archamoebea 
- Number of sequences exported - annotated: 338
- Number of sequences exported - other: 1095
Variosea 
- Number of sequences exported - annotated: 172
- Number of sequences exported - other: 485
Tubulinea 
- Number of sequences exported - annotated: 342
- Number of sequences exported - other: 3180
Centramoebia 
- Number of sequences exported - annotated: 684
- Number of sequences exported - other: 635
Flabellinia 
- Number of sequences exported - annotated: 644
- Number of sequences exported - other: 1389
Stygamoebida 
- Number of sequences exported - annotated: 13
- Number of sequences exported - other: 27


Nucleophaga 
- Number of sequences exported - annotated: 2
- Number of sequences exported - other: 9

Apicomplexa 
- Number of sequences exported - annotated: 7430
- Number of sequences exported - other: 14141

Chrompodellids 
- Number of sequences exported - annotated: 2067
- Number of sequences exported - other: 288
Alveolata_X 
- Number of sequences exported - annotated: 36
- Number of sequences exported - other: 28

Chelicerata 
- Number of sequences exported - annotated: 3471
- Number of sequences exported - other: 13904

Chlorodendrophyceae 
- Number of sequences exported - annotated: 244
- Number of sequences exported - other: 117

Chytridiomycota 
- Number of sequences exported - annotated: 1423
- Number of sequences exported - other: 1466

Labyrinthulomycetes 
- Number of sequences exported - annotated: 1399
- Number of sequences exported - other: 784

```

